### ISSUE TITLE
Cannot connect to etcd

### ISSUE THREAD

**Issue by Lanhild** [apache/apisix-docker#454]
Using the same config as [here](https://github.com/apache/apisix-docker/tree/master/example), I'm having this error:
```
apisix-dashboard_1  | {"level":"warn","ts":"2023-04-04T21:15:21.625Z","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0001648c0/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:2379: connect: connection refused\""}
```

This makes me unable to save anything in the dashboard. For example, when adding an upstream and clicking `Submit`, it loads forever.

**Comment by tanshunyuan** [comment]
maybe you can try looking at https://github.com/apache/apisix-docker/blob/master/example/docker-compose.yml#L48-L61 specifically. It can be due etcd not exposing the right port, specifically the following

```
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379" <---
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
```

**Comment by tanshunyuan** [comment]
> Though, might the issue come from the fact that I migrated from ~2.15 to 3.0?

I'm not really sure too, I didn't copy directly from [example/docker-compose.yml](https://github.com/apache/apisix-docker/blob/master/example/docker-compose.yml) instead I used [compose/docker-compose-master.yml](https://github.com/apache/apisix-docker/blob/master/compose/docker-compose-master.yaml) and retro-fitted the dashboard in as you see in my configuration below.

For at the very least, using `ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"` helped resolve the connection error
```
  apisix:
    image: 'apache/apisix:3.2.0-debian'
    container_name: apisix
    restart: always
    volumes:
      - ./gateway-config/example/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - '9180:9180/tcp'
      - '9080:9080/tcp'
      - '9091:9091/tcp'
      - '9443:9443/tcp'
    networks:
      - apisix
  dashboard:
    image: 'apache/apisix-dashboard:3.0.1-alpine'
    container_name: dashboard
    restart: always
    volumes:
      - ./gateway-config/example/dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - etcd
    ports:
      - '9000:9000/tcp'
    networks:
      - apisix
  etcd:
    image: bitnami/etcd:3.4.15
    container_name: etcd
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://etcd:2379'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
    ports:
      - '2379:2379/tcp'
    networks:
      - apisix

volumes:
  etcd_data:
    driver: local

networks:
  apisix:
    driver: bridge
```
