### ISSUE TITLE
 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)

### ISSUE THREAD

**Issue by daifuyang** [apache/apisix-docker#470]
2023-05-30 08:41:18 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:19 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:19 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:20 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:20 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:21 nginx: [emerg] still could not bind()
2023-05-30 08:42:21 
2023-05-30 08:42:21 WARNING: using fixed Admin API token has security risk.
2023-05-30 08:42:21 Please modify "admin_key" in conf/config.yaml .
2023-05-30 08:42:21 
2023-05-30 08:42:21 
2023-05-30 08:42:22 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:22 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:23 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:23 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:24 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:24 nginx: [emerg] still could not bind()

![image](https://github.com/apache/apisix-docker/assets/19951467/3d00be13-73c2-4d7b-a711-f32bf59a3867)

**Comment by daifuyang** [comment]
![image](https://github.com/apache/apisix-docker/assets/19951467/484bf3ef-b6cd-4b34-85c0-e13cd57e7c13)
![image](https://github.com/apache/apisix-docker/assets/19951467/0ef525af-b8e5-4d5b-9b9d-004ce328e297)

**Comment by daifuyang** [comment]
![image](https://github.com/apache/apisix-docker/assets/19951467/2f9887b7-0cf3-46ac-9e4a-8cc2afbaf0eb)

**Comment by mojtaba-roohi** [comment]
i have same problem,what should i do?

**Comment by daifuyang** [comment]
I commented that the 9180 port is started first and then released to start the program. This should be a bug

**Comment by laibb** [comment]
I have same problem

**Comment by Revolyssup** [comment]
@laibb Is your environment also docker desktop?

**Comment by Revolyssup** [comment]
> I commented that the 9180 port is started first and then released to start the program. This should be a bug

When the container is restarted the process terminates and the port is let go off by the previous process. I am not sure if this issue is something specific to the docker desktop environment. When you get this error, can you use netstat to check the pid of the process which is using that port and which process is that.

**Comment by moonming** [comment]
@tao12345666333 Has the dockerfile of apisix been modified recently?

**Comment by tao12345666333** [comment]
it seems there are no relevant changes. https://github.com/apache/apisix-docker/commits/master

**Comment by tao12345666333** [comment]
How did you start the container? Did you mount any directories?

**Comment by daifuyang** [comment]
我的centos服务器也有问题了

**Comment by daifuyang** [comment]
![image](https://github.com/apache/apisix-docker/assets/19951467/61097289-6fc4-49a0-b0ca-19738f5a4860)

**Comment by tao12345666333** [comment]
> How did you start the container? Did you mount any directories?

Please provide more informations.

**Comment by daifuyang** [comment]
![image](https://github.com/apache/apisix-docker/assets/19951467/ffb315aa-0d40-44a6-88e9-e7b285e641b9)

**Comment by daifuyang** [comment]
apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: apisix-dashboard
    restart: always
    volumes:
      - ~/docker-workspace/workspace/apisix/dashboard/config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    networks:
      - default

  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.3.0-centos}
    user: root
    container_name: apisix
    restart: always
    volumes:
      - ~/docker-workspace/workspace/apisix/logs:/usr/local/apisix/logs
      - ~/docker-workspace/workspace/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      # - ~/docker-workspace/workspace/apisix/go-runner:/usr/local/go-runner:ro
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      # - "9091:9091/tcp"
      # - "9443:9443/tcp"
      # - "9092:9092/tcp"
    networks:
      - default

**Comment by daifuyang** [comment]
```
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30                     # 30 seconds

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

# ext-plugin:
#   # path_for_test: /tmp/runner.sock
#   cmd: ["/usr/local/go-runner", "run"]
```

**Comment by daifuyang** [comment]
![image](https://github.com/apache/apisix-docker/assets/19951467/d3e2eb85-a3ea-47b5-9b9f-57e3af764feb)

**Comment by daifuyang** [comment]
必须注释9180重启，然后在放开。就可以了。开了restart:always

**Comment by daifuyang** [comment]
不知道是不是这个的原因

**Comment by tao12345666333** [comment]
please check this directory `~/docker-workspace/workspace/apisix/` and provide your `docker info`

**Comment by tao12345666333** [comment]
you didn't use 9180 port, right?

**Comment by daifuyang** [comment]
> 你没有使用9180端口，对吧？
yes
```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 21
  Running: 19
  Paused: 0
  Stopped: 2
 Images: 22
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.119-19.0010.ocrelease.6
 Operating System: OpenCloudOS 8.6
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.58GiB
 Name: VM-4-14-opencloudos
 ID: YH24:UINU:3QQ6:KTDE:27CR:445A:DW4C:JBHK:UNJL:BIFR:XSJ2:ES6Q
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: return1996
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.ccs.tencentyun.com/
  http://f1361db2.m.daocloud.io/
 Live Restore Enabled: false
```

**Comment by daifuyang** [comment]
![image](https://github.com/apache/apisix-docker/assets/19951467/159b606c-d86c-49d7-8983-0467c74000e4)

**Comment by daifuyang** [comment]
![image](https://github.com/apache/apisix-docker/assets/19951467/99e190e1-462c-4837-8aa4-94e6849b98db)

我注释了9180，并重启，两个都成功了。是不是端口监听冲突了？

**Comment by daifuyang** [comment]
现在是注释状态，重启容器启动了。不定时的会无法启动

**Comment by daifuyang** [comment]
![Uploading image.png…]()
现在是注释状态，重启容器启动了。不定时的会无法启动

**Comment by daifuyang** [comment]
![Uploading image.png…]()
现在是注释状态，重启容器启动了。不定时的会无法启动

**Comment by daifuyang** [comment]
现在是注释状态，重启容器启动了。不定时的会无法启动

**Comment by daifuyang** [comment]
不行，还是挂了
![image](https://github.com/apache/apisix-docker/assets/19951467/102c7b30-eb04-4343-aaf0-07f366da78a4)

**Comment by daifuyang** [comment]
![image](https://github.com/apache/apisix-docker/assets/19951467/7b69f85d-6ea2-47c9-86cb-2f073af3d311)
9080是正常

**Comment by daifuyang** [comment]
![image](https://github.com/apache/apisix-docker/assets/19951467/776ac159-0782-44ed-a8b0-186c6260d328)
正常了，但是会偶发占用的情况

**Comment by daifuyang** [comment]
服务器自启后，docker自启，然后apisix自启。无法自启。报nginx端口占用

**Comment by season886** [comment]
其实就是启动的时候不能有这个文件 /usr/local/apisix/conf/config_listen.sock，我的一直报这个错，每次进去删掉就正常

**Comment by Sn0rt** [comment]
12 july @sn0rt

**Comment by ChristophBaierATB** [comment]
## Reproduction of the Bug

### Minimal Setup

Create these two files in the same directory:

1. docker-compose.yml

   ```yaml
   version: "3"
   services:
     etcd:
       image: bitnami/etcd:3.4.15
       container_name: etcd
       environment:
         ETCD_ENABLE_V2: "true"
         ALLOW_NONE_AUTHENTICATION: "yes"
         ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
         ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
   
     apisix:
       image: apache/apisix:3.3.0-debian
       container_name: apisix
       depends_on:
         - etcd
       volumes:
         - ./config.yaml:/usr/local/apisix/conf/config.yaml:ro
   ```

2. config.yaml

   ```yaml
   deployment:
     etcd:
       host:
         - "http://etcd:2379"
       prefix: "/apisix"
       timeout: 30
   ```

Start the setup:

```bash
docker-compose up -d
```

Both services should start successfully.



### Trigger the Bug

```bash
docker kill apisix # simulate host crash
docker-compose up -d # start the container again 
docker logs apisix
```

Output:

```
...
2023/07/13 09:41:38 [emerg] 1#1: bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
...
```



### Possible Explanation

* When APISIX container starts, it creates a lock file for `config_listen.sock`, indicating that it is already in use. This prevents multiple APISIX processes from starting and accessing this socket at the same time. When the container is gracefully stopped (e.g. via `docker stop apisix`), this lock file is deleted. When the APISIX container is restarted (e.g. via `docker start apisix`), it can create a new lock file, so no problem.
* When APISIX container is shut down by force, e.g. by a host crash (simulated by `docker kill apisix`), the container will not shut down gracefully and the lock file will not be deleted. It persists within the docker container. When the host is rebooted and the APISIX container is started again, APISIX will try to create a lock file, but since such a file already exists, APISIX will think that the socket is already in use, leading to the above error message.



### Workaround Solution

It is possible to simply delete the container and start a new one that does not contain the lock file.

```bash
docker rm -f apisix
docker-compose up -d
```

However, this will not solve the problem, as it will recur every time the host crashes and restarts.
