### ISSUE TITLE
feat: if apisix.yaml file exists dont initialize it

### ISSUE THREAD

**Issue by jagedn** [apache/apisix-docker#482]
currently `apisix.yaml` file is initialized at startup in `docker-entrypoint.sh`

In case I would like to provide a configuration at startup time, and avoid to change it later, this is overwrite for the .sh

It would be great if the .sh check before if the file exists and don't overwrite in this case

**Comment by moonming** [comment]
@Sn0rt please take a look

**Comment by moonming** [comment]
@kayx23 what do you think?

**Comment by jagedn** [comment]
Let me add a little context
I'm deploying apisix in an small k8s cluster and don't want to use etcd so I deploying it as standalone. I would like to mount a config map wit routes but the .sh overwrite it so after every deployment I need to run a copy

**Comment by shreemaan-abhishek** [comment]
> In case I would like to provide a configuration at startup time
@jagedn, how do you intend to do that?

**Comment by jagedn** [comment]
Hi sorry for the late response, I was offline prev week

So, the issue is not so related with kubernetes but with the dockerfile when standalone is enabled at docker-entrypoint.sh

docker-entrypoint.sh creates 2 default files at startup: config.yaml and apisix.yaml

What I would like from this sh is not to overwrite these files if they are present (at least not overwrite apisix.yaml). To do it I think is enough to check if file exists, something as:

```
if [ ! -f "${PREFIX}/conf/apisix.yaml" ]; then
          cat > ${PREFIX}/conf/apisix.yaml << _EOC_
routes:
  -
#END
_EOC_
        fi
```

**Comment by shreemaan-abhishek** [comment]
> What I would like from this sh is not to overwrite these files

Why?

> In case I would like to provide a configuration at startup time

How?

**Comment by kamly** [comment]
I have the same problem!!

example:

apisix.yaml
```
routes:
  -
    uri: /hello
    upstream:
        nodes:
            "127.0.0.1:1980": 1
        type: roundrobin
#END
```

docker-compoase.yaml
```
services:
    apisix:
        restart: always
        image: "${IMAGE_APISIX}"
        container_name: apisix
        volumes:
            - ./etc/apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
        environment:
            - TZ=Asia/Shanghai
            - APISIX_STAND_ALONE=true
        ports:
            - "9180:9180/tcp"
            - "9080:9080/tcp"
            - "9091:9091/tcp"
            - "9443:9443/tcp" 
```

stand-alone deployment, with related routes configuration, want to overwrite apisix.yaml by mounting

run it ,  apisix.yaml will be overwritten

@shreemaan-abhishek
