### ISSUE TITLE
bug: problem with docker-entrypoint.sh for standalone mode.

### ISSUE THREAD

**Issue by shreemaan-abhishek** [apache/apisix-docker#535]
### Background
When `APISIX_STAND_ALONE=true`, and `config.yaml` is mounted. The following part of `docker-entrypoint.sh` gets executed

https://github.com/apache/apisix-docker/blob/f9b445f80fa31de1aef5fbe2ee173f9934251ea9/debian-dev/docker-entrypoint.sh#L34-L38C9

`sed -i` changes the `inode` of the mounted file from within the container which is not permitted. Hence the following error is thrown:
<img width="796" alt="image" src="https://github.com/apache/apisix-docker/assets/61597896/752cc610-c045-46ed-9575-f3654cb670ac">

### Possible fix:
use `sed -ic`

### Steps to repro:
Use the following docker-compose:

```yaml
version: "3"

services:
  apisix:
    image: apache/apisix:3.7.0-debian
    restart: always
    volumes:
      - ./apisix_conf/apisix-standalone.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    environment:
      APISIX_STAND_ALONE: true
      HTTPBIN: "httpbin.org"
      API7: "mock.api7.ai"
    networks:
      apisix:

  etcd:
    image: rancher/coreos-etcd:v3.4.15-arm64
    user: root
    restart: always
    volumes:
      - ./etcd_data:/etcd-data
    environment:
      ETCD_UNSUPPORTED_ARCH: "arm64"
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_DATA_DIR: "/etcd-data"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
```
