### ISSUE TITLE
Apisix port 9091 not listening

### ISSUE THREAD

**Issue by dani7lb** [apache/apisix-docker#550]
Hello everyone,

I have an Apisix (3.8.0-debian) instance running on Docker Desktop (4.28.0). When i try to connect it to Prometheus i noticed the default port (9091) is not listening. Making some tests i figured out only ports 9080, 9180 and 9443 are listening. When using cURL from WSL it returns: Empty response. When using cURL from other docker on same network it returns: connection refused.
There are no errors on logs or any error message. Does anyone know why?

Here is the docker deployment command:
```
APISIX_DEPLOYMENT_ETCD_HOST="[\"http://$etcd_ip:2379\"]"
docker run -d --name "apisix" --network=apisix \
    -p19080:9080 -p19180:9180 -p19443:9443 -p19091:9091 -p19092:9092 -p19100:9100 \
    -e APISIX_DEPLOYMENT_ETCD_HOST=${APISIX_DEPLOYMENT_ETCD_HOST} \
    apache/apisix:3.8.0-debian
```

Here is my config.yaml:
```
apisix:
  enable_control: true
  control:
    ip: "127.0.0.1"
    port: 9092
  router:
    http: "radixtree_uri_with_parameter"
deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key_required: true
    admin_key:
      - name: root
        key: bB3XBu6shJRbkotW7ngVw6HQnseFafyTgdH==
        role: admin
      - name: dleandro
        key:QnseFafyTgdHm0Vy54Gv2OAyobwKwPDOk7==
        role: admin
    allow_admin:
      - 172.22.0.1
  plugin_attr:
    prometheus:
      export_uri: /apisix/prometheus/metrics
      export_addr:
        ip: 0.0.0.0
        port: 9091
      enable_export_server: true
  etcd:
    host:
      - "http://172.22.0.2:2379"
plugins:
  - ip-restriction                  # priority: 3000
  - ldap-auth                       # priority: 2540
  - jwt-auth                         # priority: 2510
  - proxy-rewrite                 # priority: 1008
  - server-info                     # priority: 990
  - public-api                      # priority: 501
  - prometheus                   # priority: 500
stream_plugins:
  - ip-restriction                  # priority: 3000
  - prometheus                   # priority: 500
```
If you need some other information ill be glad to post it.
