### ISSUE TITLE
entrypoint.sh is trying to update config.yaml in read only file system

### ISSUE THREAD

**Issue by TheShubhendra** [apache/apisix-docker#557]
I am encountering an issue with Apache APISIX in standalone mode where the container fails to start due to repeated `sed: cannot rename /usr/local/apisix/conf/sedXXXXXX: Device or resource busy` errors. This occurs when trying to use docker-compose to deploy APISIX with configuration files mounted as volumes.

## docker-compose.yaml
```yaml

version: "3"

services:
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.6.0-debian}
    restart: always
    volumes:
      - ./config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    environment:
      - APISIX_STAND_ALONE=true
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
```
## config.yaml
```yaml
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

plugins:
  - opentelemetry
  - proxy-rewrite
  - proxy-cache
  - real-ip
  - serverless-post-function
  - jwt-auth


plugin_attr:
  opentelemetry:
    resource:
      service.name: apisix
      service.namespace: learning-app
      deployment.environment: production
    collector:
      address: http://127.0.0.1:4318
      request_timeout: 3
```
